function caseSensFunc(wordBank, length) {
    let password = "";
  
    for (let i = 0; i < length; i++) {
      const randIndex = Math.floor(Math.random() * wordBank.length);
      const randomWord = wordBank[randIndex];
      const useUppercase = Math.random() < 0.4; // 40% chance of using uppercase on a random run
  
      if (useUppercase) {
        password += randomWord.toUpperCase();
      } else {
        password += randomWord;
      }
    }
  
    return password;
  }

  
  const password = caseSensFunc(wordBank, 3); // 3 words generated by default with mixed case
  console.log(password);  